version: '2.3'
services:
  # Mongodb
  #-----------------
#  mongo:
#    image: mongo:3.6
#    container_name:  ${COMPOSE_PROJECT_NAME}_mongo
#    networks:
#      - unifi
#    restart: always
#    volumes:
#      - '$HOME/networks/docker/mongodb/db:/data/db'
#      - '$HOME/networks/docker/mongodb/dbcfg:/data/configdb'

  # UniFi Controller
  #-----------------
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: ${COMPOSE_PROJECT_NAME}_controller
#    depends_on:
#     - mongo
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - '$HOME/networks/docker/unifi/dir:/unifi'
      - '$HOME/networks/docker/unifi/data:/unifi/data'
      - '$HOME/networks/docker/unifi/log:/unifi/log'
      - '$HOME/networks/docker/unifi/cert:/unifi/cert'
      - '$HOME/networks/docker/unifi/init:/unifi/init.d'
      - '$HOME/networks/docker/unifi/run:/var/run/unifi'
     # Mount local folder for backups and autobackups
     #- '$HOME/networks/docker/pihole/unifi/backup:/unifi/data/backup'
#    user: unifi
#    sysctls:
#      net.ipv4.ip_unprivileged_port_start: 0
    environment:
       RUNAS_UID0: 'false'
 #     DB_URI: '$HOME/networks/docker/mongodb://mongo/unifi'
 #     STATDB_URI: '$HOME/networks/docker/mongodb://mongo/unifi_stat'
 #     DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery

  # UniFi Logs
  #-----------
  logs:
    image: bash
    container_name: ${COMPOSE_PROJECT_NAME}_logs
    depends_on:
      - controller
    command: bash -c 'tail -F $HOME/networks/docker/unifi/log/*.log'
    restart: always
    volumes:
      - '$HOME/networks/docker/unifi/log:/unifi/log'

#volumes:
#  db:
#  dbcfg:
#  data:
#  log:
#  cert:
#  init:
#  dir:
#  run:

networks:
  unifi:
