version: "3.8"
services:
  # Portainer
  #----------
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:linux-arm
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - '$HOME/networks/docker/portainer/var/run/docker.sock:/var/run/docker.sock:ro'
      - '$HOME/networks/docker/portainer/etc/localtime:/etc/localtime:ro'
      - '$HOME/networks/docker/portainer/etc/timezone:/etc/timezone:ro'
      - '$HOME/networks/docker/portainer/data/:/data'
